/**
 * Regenerate src/auth/public-suffix-list.ts from the Public Suffix List.
 *
 * The embedded PSL is DATA, not a dependency — the project is self-contained. Regenerate
 * it periodically (the list changes) with:
 *
 *   curl -fsS https://publicsuffix.org/list/public_suffix_list.dat -o /tmp/psl.dat
 *   node scripts/generate-psl.mjs /tmp/psl.dat src/auth/public-suffix-list.ts
 *
 * Both the ICANN and PRIVATE sections are included: for DMARC that is the SAFE direction
 * (it only makes an organizational domain more specific, never shorter, so it can never
 * align two unrelated registrants), and it lets the algorithm pass the canonical
 * publicsuffix.org test suite (which covers private suffixes such as uk.com). Rules are
 * normalised to punycode via node:url domainToASCII so IDN domains match.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { domainToASCII } from 'node:url';

const [, , input, output] = process.argv;
if (input === undefined || output === undefined) {
  console.error('usage: node scripts/generate-psl.mjs <public_suffix_list.dat> <out.ts>');
  process.exit(1);
}

const norm = (d) => {
  const a = domainToASCII(d);
  return a === '' ? d.toLowerCase() : a;
};

const rules = [], wildcards = [], exceptions = [];
for (const raw of readFileSync(input, 'utf8').split('\n')) {
  const line = raw.trim();
  if (line === '' || line.startsWith('//')) continue; // comments incl. the section markers
  const rule = line.split(/\s/)[0];
  if (rule.startsWith('!')) exceptions.push(norm(rule.slice(1)));
  else if (rule.startsWith('*.')) wildcards.push(norm(rule.slice(2)));
  else rules.push(norm(rule));
}
const uniq = (a) => [...new Set(a)].sort();
const R = uniq(rules), W = uniq(wildcards), E = uniq(exceptions);

const out = `/**
 * The Public Suffix List (publicsuffix.org), embedded as data — the authority on where a
 * registered domain sits under a public suffix, used by DMARC org-domain alignment.
 *
 * GENERATED by scripts/generate-psl.mjs from publicsuffix.org/list/public_suffix_list.dat
 * (the FULL list — both ICANN and PRIVATE sections; see that script for why). Do not edit
 * by hand; regenerate to update. Rules are normalised to punycode so IDN domains match.
 * Embedded rather than taken as a runtime dependency — the project is self-contained.
 *
 * ${R.length} normal rules, ${W.length} wildcard rules, ${E.length} exception rules.
 */

export const PSL_RULES: ReadonlySet<string> = new Set(\n${JSON.stringify(R)}\n);
export const PSL_WILDCARDS: ReadonlySet<string> = new Set(${JSON.stringify(W)});
export const PSL_EXCEPTIONS: ReadonlySet<string> = new Set(${JSON.stringify(E)});
`;
writeFileSync(output, out);
console.log(`wrote ${output}: ${R.length} normal, ${W.length} wildcard, ${E.length} exception`);
